name: CI/CD for nest app

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main


jobs:
    build:
        runs-on: ubuntu-latest

        steps:

          - name: Checkout code
            uses: actions/checkout@v2
            
          - name: setup nodejs
            uses: actions/setup-node@v2 
            with:
               node-version: '18' 
               
          - name: install depend
            run: | 
                npm install